export const CLICK_NEXT_BUTTON = 'CLICK_NEXT_BUTTON';
export const CLICK_PREVIOUS_BUTTON = 'CLICK_PREVIOUS_BUTTON';
export const CLICK_VALIDATION_BUTTON = 'CLICK_VALIDATION_BUTTON';
export const CLICK_SYNTHESIS_BUTTON = 'CLICK_SYNTHESIS_BUTTON';
export const CLICK_COURSE_LINK = 'CLICK_COURSE_LINK';